substitutions:
  DEVICE_NAME: todoist-display

esphome:
  name: ${DEVICE_NAME}
  friendly_name: Todoist Display
  # Keep custom partitions configuration
  platformio_options:
    board_upload.maximum_ram_size: 327680
    board_upload.maximum_size: 16777216
    board_build.partitions: "../../../custom_partitions_3584.csv"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  flash_size: 16MB

# Enable logging for debugging
logger:
  level: INFO

# Enable OTA updates
ota:
  password: "ota_password"

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Web server for easy access
web_server:
  port: 80

# Time component for displaying current time
time:
  - platform: sntp
    id: system_time
    timezone: Europe/Amsterdam

# Use the modified SC01 Plus display component
external_components:
  - source:
      type: local
      path: ../components
    components: [ hd_device_sc01_plus, todoist ]

# Configure the display
hd_device_sc01_plus:
  id: device
  brightness: 75
  todoist_api_key: !secret todoist_api_key

# Basic brightness control
number:
  - platform: template
    id: screen_brightness
    name: Screen brightness
    min_value: 0
    max_value: 100
    step: 5
    initial_value: 75
    restore_value: true
    set_action:
      - lambda: |-
          id(device).set_brightness(x);

# Todoist configuration will be added in Phase 3
