substitutions:
  DEVICE_NAME: todoist-display

esphome:
  name: ${DEVICE_NAME}
  friendly_name: Todoist Display
  # Keep custom partitions configuration
  platformio_options:
    board_upload.maximum_ram_size: 327680
    board_upload.maximum_size: 16777216
    board_build.partitions: "../../../custom_partitions_3584.csv"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  flash_size: 16MB
  # Add watchdog to auto-restart if something hangs
  restore_from_flash: true

# Enhanced logging for better debugging
logger:
  level: INFO
  # Add separate log levels for components
  logs:
    todoist: DEBUG
    todoist.api: INFO
    wifi: INFO
    http_request: INFO

# Enable better OTA updates with timeout and retry
ota:
  password: !secret ota_password
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5

# WiFi configuration with optimized connection settings
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none
  
  # Enable fallback hotspot in case WiFi connection fails
  ap:
    ssid: "Todoist Display Fallback"
    password: !secret fallback_password

# Add Safe Mode button if everything else fails
button:
  - platform: safe_mode
    name: "Restart in Safe Mode"
    id: safe_mode_btn

# Web server for easy access
web_server:
  port: 80

# Add a status sensor to display in Home Assistant
sensor:
  - platform: wifi_signal
    name: "Todoist Display WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Todoist Display Uptime"
    update_interval: 60s

# Time component for displaying current time and handling due dates
time:
  - platform: sntp
    id: system_time
    timezone: Europe/Amsterdam
    on_time_sync:
      then:
        - logger.log: "Time synchronized"

# Use the modified SC01 Plus display component
external_components:
  - source:
      type: local
      path: ../components
    components: [ hd_device_sc01_plus, todoist ]

# Configure the display
hd_device_sc01_plus:
  id: device
  brightness: 75

# Configure Todoist component
todoist:
  id: todoist
  todoist_api_key: !secret todoist_api_key
  time_id: system_time
  interval: 300s  # Update every 5 minutes

# Basic brightness control
number:
  - platform: template
    id: screen_brightness
    name: Screen brightness
    min_value: 0
    max_value: 100
    step: 5
    initial_value: 75
    restore_value: true
    set_action:
      - lambda: |-
          id(device).set_brightness(x);
